### ISSUE TITLE
matlab should restart when using minTV.mexw64

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#18] opened 2016-09-30 03:21 UTC
I'm testing my projection files using d09_Algorithms04.m and several minutes later matlab hint that it should restart. 
Here are the crash log files, could you please tell me what's the matter? Thank you!
[matlab_crash_dump.txt](https://github.com/CERN/TIGRE/files/502113/matlab_crash_dump.txt)

**Comment by AnderBiguri** [comment] 2016-09-30 07:45
Hi @ilanzhang ,
I have heard of someone else having problems with this function but I am unable to reproduce it on any of my PCs. Could you please answer and try the following things?:

1. Do the rest of the demos work OK?
2. When does this exactly crash? Can you , instead of running the whole demo, run the algorithms independently? Is this algorithm specific or all 3 TV algorithms that use it crash?
3. Try changing line 45 to `geo.nVoxel=[128;128;128]/4;`. Does it work now?
4. Can you tell us the specifications of your PC? Os, MATLAB version, compiler and GPU?

Hopefully we can fin a fix. 
Best,
Ander

**Comment by ilanzhang** [comment] 2016-10-10 12:21
Hi, @AnderBiguri ,
Sorry having been late cause the National Day. Yes,all the demos except the d09_Algorithms04.m. work OK and at first it crashed when appling minTV.mex, but it works well after substituting f=minimizeTV(f0,dtvg,ng); with the CPU codes. But now another crash comes with the application with tvDenoing in 
imgO=(permute(tvDenoise(permute(img,[3 2 1]),hyper,iter),[1 2 3]));
in im3DDenosing.m in SART_TV.m.
For my computer, win7 ultimate, matlab 2014b, VC++2012 and GTX660.

**Comment by AnderBiguri** [comment] 2016-10-10 12:36
Hi @ilanzhang,
If you still want to look at fixing the GPU part of `minimizeTV`, please, could you answer to all of my questions before? 

If you are OK with using CPU code, no worries. However, can you tell me what happens in that line in `tvDenoise` ? What do you mean it crashes ? is there any error there?

Sorry for the questions, I just can not reproduce any of those errors, and I would like to fix them, but I need help for that, as I can not see it! 
Also, what version of windows are you using? 64 bits?

**Comment by ilanzhang** [comment] 2016-10-10 12:45
Matlab just hint me that **MATLAB has encountered an internal problem and needs to close**. yes, 64bits.

**Comment by AnderBiguri** [comment] 2016-10-10 12:53
@ilanzhang  Unfortunately I do not have CPU code for that function. It is very strange, as I know of someone else that has this problem sometimes, but there is a lot of people that has no problem. Can you please, try running the code again but with `geo.nVoxel=[128;128;128]/4;`? I want to make sure that Memory is not an issue.

**Comment by ilanzhang** [comment] 2016-10-10 13:25
OK! Probably the problem is exactly here. The demo just work well when changed with `geo.nVoxel=[128;128;128]/4;`! Thank you!

**Comment by AnderBiguri** [comment] 2016-10-10 13:38
Hi @ilanzhang , just to make compeltely sure: did the demo work OK with the GPU part? with `minTV`? If you didn't try, can you please try it for me? I wan't to make sure this was just a memory problem and not a code problem ;)

**Comment by ilanzhang** [comment] 2016-10-10 13:41
Yes, The code run well with the GPU part, no matter minTV or tvDenoising.But something happened when appling my projections, I'm trying to figure out what's wrong.

**Comment by AnderBiguri** [comment] 2016-10-10 13:42
@ilanzhang  Great, good to know. I am going to close this issue on Github, but please, if you have specific problems with your code, send us an email to tigre.toolbox@gmail.com or a.biguri@bath.ac.uk .
Best Ander

**Closed** 2016-10-10 13:43 UTC
Labels: bug, help wanted

**Comment by ilanzhang** [comment] 2016-10-10 13:45
@AnderBiguri 
Thank you very much! I'll send to you if I have some other problems!

**Comment by Stemmaker** [comment] 2019-08-15 09:10
> I'm testing my projection files using d09_Algorithms04.m and several minutes later matlab hint that it should restart.
> Here are the crash log files, could you please tell me what's the matter? Thank you!
> [matlab_crash_dump.txt](https://github.com/CERN/TIGRE/files/502113/matlab_crash_dump.txt)

Hello! I've been using the TIGER toolbook for a short time, and I always  encounter a problem about the minTV program(i.e. minimizeTV.m), that says, undefined function or variable 'minTV'.
Could you please help me to solve it? Thank you.

**Comment by AnderBiguri** [comment] 2019-08-15 09:17
@Stemmaker Have you compiled it? If compilation was successful, then it should exist in 

`./TIGRE/MATLAB/Mex_files/(yourOS)/minTV.mexXXX 
`
e.g. for  a 64 bit widows:

`./TIGRE/MATLAB/Mex_files/win64/minTV.mexw64
`

**Comment by Stemmaker** [comment] 2019-08-16 02:31
@AnderBiguri 
Thanks for your reply. I found the minTV.mexw64, and now it can run. However, it was stopped by another error:
Invalid MEX-file 'D:\MATLAB\R2017a\bin\CSET-master\TV minimization\minTV.mexw64': Missing dependent shared libraries:
'cudart64_92.dll' required by 'D:\MATLAB\R2017a\bin\CSET-master\TV minimization\minTV.mexw64'.

**Comment by AnderBiguri** [comment] 2019-08-16 07:00
Have you compiled the toolbox yourself?

**Comment by Stemmaker** [comment] 2019-08-19 13:30
I'm so sorry to reply late, and I  compiled the toolbox by running Compile.m, but it indicated that no supported compiler or SDK was found. So, I try to install a C++ compiler (MVS2013), but it still indicated that mex_CUDA_win64.xml was not found. Therefore, I had to try to install a CUDA toolkit.
Hope that I can succeed in compiling it. I'll show you more progress soon.
One more question, why can I use the compiled mex files in the Mex_files directly?

**Comment by Stemmaker** [comment] 2019-08-19 13:31
@AnderBiguri

**Comment by AnderBiguri** [comment] 2019-08-19 13:34
@Stemmaker  Have you followed the instructions? There are clear instructions on how to set up, install and compile TIGRE. 

https://github.com/CERN/TIGRE/blob/master/Frontispiece/MATLAB_installation.md

You need to Compile the code for your machine yourself, you can not use the provided mex files unless you have 100% the same hardware and software configuration as me, which is unlikely. Follow those instructions and if it does not work, let me know in which step it fails.

**Comment by Stemmaker** [comment] 2019-08-19 14:01
OK!
